import { categories } from "@/lib/constants"
import type { BuilderProfile, ProjectRecord, ProjectComment } from "@/lib/types"

export const demoBuilders: BuilderProfile[] = [
  {
    id: "demo-builder-1",
    email: "ava@example.com",
    fullName: "Ava Moreno",
    username: "avamoreno",
    avatarUrl: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=240&q=80",
    bio: "Shipping small AI tools and internal workflows for product teams.",
    isAdmin: true,
    twitterUrl: "https://twitter.com/avamoreno",
    githubUrl: "https://github.com/avamoreno",
    followerCount: 428,
    projectCount: 12,
  },
  {
    id: "demo-builder-2",
    email: "noah@example.com",
    fullName: "Noah Walker",
    username: "noahbuilds",
    avatarUrl: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=240&q=80",
    bio: "Focused on AI-native products for research, education, and support.",
    twitterUrl: "https://twitter.com/noahbuilds",
    followerCount: 156,
    projectCount: 5,
  },
  {
    id: "demo-builder-3",
    email: "maya@example.com",
    fullName: "Maya Chen",
    username: "mayaships",
    avatarUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=240&q=80",
    bio: "Designing tiny tools for founders, marketers, and community teams.",
    twitterUrl: "https://twitter.com/mayaships",
    githubUrl: "https://github.com/mayaships",
    followerCount: 233,
    projectCount: 8,
  },
  {
    id: "demo-builder-4",
    email: "eli@example.com",
    fullName: "Eli Brooks",
    username: "elibuilds",
    avatarUrl: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=240&q=80",
    bio: "Building practical agent workflows for operations teams.",
    twitterUrl: "https://twitter.com/elibuilds",
    githubUrl: "https://github.com/elibuilds",
    followerCount: 319,
    projectCount: 9,
  },
  {
    id: "demo-builder-5",
    email: "sara@example.com",
    fullName: "Sara Patel",
    username: "sarap",
    avatarUrl: "https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=240&q=80",
    bio: "Experimenting with education, health, and finance products.",
    twitterUrl: "https://twitter.com/sarap",
    followerCount: 184,
    projectCount: 6,
  },
  {
    id: "demo-builder-6",
    email: "leo@example.com",
    fullName: "Leo Grant",
    username: "leogrant",
    avatarUrl: "https://images.unsplash.com/photo-1519345182560-3f2917c472ef?auto=format&fit=crop&w=240&q=80",
    bio: "Vibecoding polished SaaS ideas and launch experiments.",
    githubUrl: "https://github.com/leogrant",
    followerCount: 267,
    projectCount: 10,
  },
]

export const demoProjects: ProjectRecord[] = [
  {
    id: "demo-project-1",
    slug: "promptlane",
    status: "approved",
    hasPendingRevision: false,
    name: "Promptlane",
    tagline: "Turn repeat prompts into reusable product playbooks.",
    description:
      "Promptlane helps teams capture the prompts, datasets, and notes behind recurring AI tasks so anyone on the team can reuse what works.",
    projectUrl: "https://example.com/promptlane",
    category: categories[0],
    techStack: ["Next.js", "Supabase", "OpenAI"],
    projectTags: ["SaaS", "Developer Tool", "Workflow"],
    helpTags: ["Security", "Design"],
    thumbnailUrl: "https://images.unsplash.com/photo-1558655146-d09347e92766?auto=format&fit=crop&w=1200&q=80",
    screenshotUrls: [
      "https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&w=1200&q=80",
    ],
    rejectionReason: null,
    reviewNotes: null,
    createdAt: "2026-04-15T12:00:00.000Z",
    updatedAt: "2026-04-17T12:00:00.000Z",
    submittedAt: "2026-04-15T12:00:00.000Z",
    revisionNumber: 1,
    owner: demoBuilders[0],
    isLive: true,
    viewCount: 1240,
    heartCount: 42,
  },
  {
    id: "demo-project-2",
    slug: "classnote-ai",
    status: "approved",
    hasPendingRevision: false,
    name: "Classnote AI",
    tagline: "A lesson recap companion for teachers and students.",
    description:
      "Teachers upload notes and generate clean summaries, quizzes, and study cards from a single workspace built for classroom use.",
    projectUrl: "https://example.com/classnote",
    category: categories[6],
    techStack: ["Next.js", "TypeScript", "Supabase"],
    projectTags: ["Education", "Productivity"],
    helpTags: ["Collab", "Product Feedback"],
    thumbnailUrl: "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=1200&q=80",
    screenshotUrls: [
      "https://images.unsplash.com/photo-1516321497487-e288fb19713f?auto=format&fit=crop&w=1200&q=80",
    ],
    rejectionReason: null,
    reviewNotes: null,
    createdAt: "2026-04-10T12:00:00.000Z",
    updatedAt: "2026-04-18T12:00:00.000Z",
    submittedAt: "2026-04-10T12:00:00.000Z",
    revisionNumber: 2,
    owner: demoBuilders[1],
    isLive: true,
    viewCount: 890,
    heartCount: 28,
  },
  {
    id: "demo-project-3",
    slug: "agentdesk",
    status: "approved",
    hasPendingRevision: false,
    name: "AgentDesk",
    tagline: "Route messy customer requests to the right AI workflow.",
    description:
      "AgentDesk turns support inbox patterns into guided agent tasks, with review checkpoints before anything reaches a customer.",
    projectUrl: "https://example.com/agentdesk",
    category: categories[4],
    techStack: ["Next.js", "OpenAI", "Postgres"],
    projectTags: ["AI Agent", "Workflow", "SaaS"],
    helpTags: ["Security", "Product Feedback"],
    thumbnailUrl: "https://images.unsplash.com/photo-1553877522-43269d4ea984?auto=format&fit=crop&w=1200&q=80",
    screenshotUrls: ["https://images.unsplash.com/photo-1551434678-e076c223a692?auto=format&fit=crop&w=1200&q=80"],
    rejectionReason: null,
    reviewNotes: null,
    createdAt: "2026-04-12T12:00:00.000Z",
    updatedAt: "2026-04-19T12:00:00.000Z",
    submittedAt: "2026-04-12T12:00:00.000Z",
    revisionNumber: 2,
    owner: demoBuilders[3],
    isLive: true,
    viewCount: 760,
    heartCount: 35,
  },
  {
    id: "demo-project-4",
    slug: "launchbrief",
    status: "approved",
    hasPendingRevision: false,
    name: "LaunchBrief",
    tagline: "Generate launch pages, email angles, and QA notes from one brief.",
    description:
      "LaunchBrief helps indie builders shape a release plan by turning product notes into copy, checklists, and feedback prompts.",
    projectUrl: "https://example.com/launchbrief",
    category: categories[3],
    techStack: ["Remix", "Claude", "Tailwind"],
    projectTags: ["Marketing", "Productivity", "Workflow"],
    helpTags: ["Growth", "Design"],
    thumbnailUrl: "https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=1200&q=80",
    screenshotUrls: ["https://images.unsplash.com/photo-1516321497487-e288fb19713f?auto=format&fit=crop&w=1200&q=80"],
    rejectionReason: null,
    reviewNotes: null,
    createdAt: "2026-04-13T12:00:00.000Z",
    updatedAt: "2026-04-20T12:00:00.000Z",
    submittedAt: "2026-04-13T12:00:00.000Z",
    revisionNumber: 1,
    owner: demoBuilders[2],
    isLive: true,
    viewCount: 640,
    heartCount: 31,
  },
  {
    id: "demo-project-5",
    slug: "folioforge",
    status: "approved",
    hasPendingRevision: false,
    name: "FolioForge",
    tagline: "A portfolio generator for builders with messy project notes.",
    description:
      "FolioForge turns screenshots, changelogs, and short notes into polished project stories that are easy to publish.",
    projectUrl: "https://example.com/folioforge",
    category: categories[2],
    techStack: ["Astro", "TypeScript", "Vercel"],
    projectTags: ["Portfolio", "Design", "Developer Tool"],
    helpTags: ["Design", "Growth"],
    thumbnailUrl: "https://images.unsplash.com/photo-1498050108023-c5249f4df085?auto=format&fit=crop&w=1200&q=80",
    screenshotUrls: ["https://images.unsplash.com/photo-1518005020951-eccb494ad742?auto=format&fit=crop&w=1200&q=80"],
    rejectionReason: null,
    reviewNotes: null,
    createdAt: "2026-04-08T12:00:00.000Z",
    updatedAt: "2026-04-21T12:00:00.000Z",
    submittedAt: "2026-04-08T12:00:00.000Z",
    revisionNumber: 3,
    owner: demoBuilders[5],
    isLive: true,
    viewCount: 1180,
    heartCount: 56,
  },
  {
    id: "demo-project-6",
    slug: "cartpilot",
    status: "approved",
    hasPendingRevision: false,
    name: "CartPilot",
    tagline: "An AI assistant for small storefront merchandising.",
    description:
      "CartPilot reviews product catalogs, spots weak listings, and suggests bundles, copy, and seasonal campaigns for small shops.",
    projectUrl: "https://example.com/cartpilot",
    category: categories[5],
    techStack: ["Next.js", "Stripe", "Supabase"],
    projectTags: ["E-commerce", "SaaS", "AI Agent"],
    helpTags: ["Security", "Performance"],
    thumbnailUrl: "https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?auto=format&fit=crop&w=1200&q=80",
    screenshotUrls: ["https://images.unsplash.com/photo-1556742502-ec7c0e9f34b1?auto=format&fit=crop&w=1200&q=80"],
    rejectionReason: null,
    reviewNotes: null,
    createdAt: "2026-04-07T12:00:00.000Z",
    updatedAt: "2026-04-16T12:00:00.000Z",
    submittedAt: "2026-04-07T12:00:00.000Z",
    revisionNumber: 1,
    owner: demoBuilders[0],
    isLive: true,
    viewCount: 990,
    heartCount: 44,
  },
  {
    id: "demo-project-7",
    slug: "studyloop",
    status: "approved",
    hasPendingRevision: false,
    name: "StudyLoop",
    tagline: "Turn class recordings into study plans that adapt each week.",
    description:
      "StudyLoop creates summaries, flashcards, and gentle review schedules from lectures so students can keep momentum.",
    projectUrl: "https://example.com/studyloop",
    category: categories[6],
    techStack: ["React", "Whisper", "Firebase"],
    projectTags: ["Education", "Productivity", "AI Agent"],
    helpTags: ["Product Feedback", "Design"],
    thumbnailUrl: "https://images.unsplash.com/photo-1524995997946-a1c2e315a42f?auto=format&fit=crop&w=1200&q=80",
    screenshotUrls: ["https://images.unsplash.com/photo-1513258496099-48168024aec0?auto=format&fit=crop&w=1200&q=80"],
    rejectionReason: null,
    reviewNotes: null,
    createdAt: "2026-04-06T12:00:00.000Z",
    updatedAt: "2026-04-14T12:00:00.000Z",
    submittedAt: "2026-04-06T12:00:00.000Z",
    revisionNumber: 2,
    owner: demoBuilders[4],
    isLive: true,
    viewCount: 705,
    heartCount: 26,
  },
  {
    id: "demo-project-8",
    slug: "clubroom",
    status: "approved",
    hasPendingRevision: false,
    name: "Clubroom",
    tagline: "A lightweight community hub for tiny paid groups.",
    description:
      "Clubroom gives creators member posts, event reminders, and resource drops without the weight of a full community platform.",
    projectUrl: "https://example.com/clubroom",
    category: categories[7],
    techStack: ["Rails", "Hotwire", "Stripe"],
    projectTags: ["Social", "Marketplace", "SaaS"],
    helpTags: ["Growth", "Collab"],
    thumbnailUrl: "https://images.unsplash.com/photo-1517048676732-d65bc937f952?auto=format&fit=crop&w=1200&q=80",
    screenshotUrls: ["https://images.unsplash.com/photo-1529156069898-49953e39b3ac?auto=format&fit=crop&w=1200&q=80"],
    rejectionReason: null,
    reviewNotes: null,
    createdAt: "2026-04-05T12:00:00.000Z",
    updatedAt: "2026-04-13T12:00:00.000Z",
    submittedAt: "2026-04-05T12:00:00.000Z",
    revisionNumber: 1,
    owner: demoBuilders[2],
    isLive: true,
    viewCount: 534,
    heartCount: 22,
  },
  {
    id: "demo-project-9",
    slug: "cashcanvas",
    status: "approved",
    hasPendingRevision: false,
    name: "CashCanvas",
    tagline: "A visual finance planner for freelancers with uneven income.",
    description:
      "CashCanvas turns invoices, goals, and recurring bills into a simple planning board for solo operators.",
    projectUrl: "https://example.com/cashcanvas",
    category: categories[1],
    techStack: ["Next.js", "Plaid", "Postgres"],
    projectTags: ["Finance", "Productivity", "SaaS"],
    helpTags: ["Security", "Product Feedback"],
    thumbnailUrl: "https://images.unsplash.com/photo-1554224155-6726b3ff858f?auto=format&fit=crop&w=1200&q=80",
    screenshotUrls: ["https://images.unsplash.com/photo-1554224154-26032ffc0d07?auto=format&fit=crop&w=1200&q=80"],
    rejectionReason: null,
    reviewNotes: null,
    createdAt: "2026-04-04T12:00:00.000Z",
    updatedAt: "2026-04-12T12:00:00.000Z",
    submittedAt: "2026-04-04T12:00:00.000Z",
    revisionNumber: 2,
    owner: demoBuilders[4],
    isLive: true,
    viewCount: 812,
    heartCount: 38,
  },
  {
    id: "demo-project-10",
    slug: "healthprompt",
    status: "approved",
    hasPendingRevision: false,
    name: "HealthPrompt",
    tagline: "Draft patient-friendly intake questions from care goals.",
    description:
      "HealthPrompt helps small clinics prototype intake flows and patient education prompts before handing them to clinical review.",
    projectUrl: "https://example.com/healthprompt",
    category: categories[0],
    techStack: ["SvelteKit", "OpenAI", "Supabase"],
    projectTags: ["Health", "Developer Tool", "Workflow"],
    helpTags: ["Security", "Product Feedback"],
    thumbnailUrl: "https://images.unsplash.com/photo-1576091160550-2173dba999ef?auto=format&fit=crop&w=1200&q=80",
    screenshotUrls: ["https://images.unsplash.com/photo-1579684385127-1ef15d508118?auto=format&fit=crop&w=1200&q=80"],
    rejectionReason: null,
    reviewNotes: null,
    createdAt: "2026-04-03T12:00:00.000Z",
    updatedAt: "2026-04-11T12:00:00.000Z",
    submittedAt: "2026-04-03T12:00:00.000Z",
    revisionNumber: 1,
    owner: demoBuilders[5],
    isLive: true,
    viewCount: 458,
    heartCount: 19,
  },
  {
    id: "demo-project-11",
    slug: "briefbot",
    status: "approved",
    hasPendingRevision: false,
    name: "BriefBot",
    tagline: "Turn Slack threads into clean product decision briefs.",
    description:
      "BriefBot pulls scattered discussion into decision logs, owner lists, and next-step summaries for fast-moving teams.",
    projectUrl: "https://example.com/briefbot",
    category: categories[0],
    techStack: ["Node.js", "Slack API", "OpenAI"],
    projectTags: ["Developer Tool", "Productivity", "Workflow"],
    helpTags: ["Performance", "Security"],
    thumbnailUrl: "https://images.unsplash.com/photo-1611224923853-80b023f02d71?auto=format&fit=crop&w=1200&q=80",
    screenshotUrls: ["https://images.unsplash.com/photo-1552664730-d307ca884978?auto=format&fit=crop&w=1200&q=80"],
    rejectionReason: null,
    reviewNotes: null,
    createdAt: "2026-04-02T12:00:00.000Z",
    updatedAt: "2026-04-10T12:00:00.000Z",
    submittedAt: "2026-04-02T12:00:00.000Z",
    revisionNumber: 2,
    owner: demoBuilders[3],
    isLive: true,
    viewCount: 932,
    heartCount: 41,
  },
  {
    id: "demo-project-12",
    slug: "moodboard-ai",
    status: "approved",
    hasPendingRevision: false,
    name: "Moodboard AI",
    tagline: "Collect references and turn them into usable brand directions.",
    description:
      "Moodboard AI helps solo founders shape visual direction from screenshots, notes, and competitor references.",
    projectUrl: "https://example.com/moodboard-ai",
    category: categories[2],
    techStack: ["Next.js", "Replicate", "Tailwind"],
    projectTags: ["Design", "Portfolio", "AI Agent"],
    helpTags: ["Design", "Product Feedback"],
    thumbnailUrl: "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1200&q=80",
    screenshotUrls: ["https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?auto=format&fit=crop&w=1200&q=80"],
    rejectionReason: null,
    reviewNotes: null,
    createdAt: "2026-04-01T12:00:00.000Z",
    updatedAt: "2026-04-09T12:00:00.000Z",
    submittedAt: "2026-04-01T12:00:00.000Z",
    revisionNumber: 1,
    owner: demoBuilders[2],
    isLive: true,
    viewCount: 674,
    heartCount: 29,
  },
  {
    id: "demo-project-13",
    slug: "opsrelay",
    status: "approved",
    hasPendingRevision: false,
    name: "OpsRelay",
    tagline: "A handoff tracker for recurring operations work.",
    description:
      "OpsRelay gives teams a shared view of weekly checklists, blockers, and AI-generated handoff notes.",
    projectUrl: "https://example.com/opsrelay",
    category: categories[1],
    techStack: ["Vue", "Supabase", "OpenAI"],
    projectTags: ["Workflow", "Productivity", "SaaS"],
    helpTags: ["Collab", "Performance"],
    thumbnailUrl: "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?auto=format&fit=crop&w=1200&q=80",
    screenshotUrls: ["https://images.unsplash.com/photo-1553877522-43269d4ea984?auto=format&fit=crop&w=1200&q=80"],
    rejectionReason: null,
    reviewNotes: null,
    createdAt: "2026-03-31T12:00:00.000Z",
    updatedAt: "2026-04-08T12:00:00.000Z",
    submittedAt: "2026-03-31T12:00:00.000Z",
    revisionNumber: 2,
    owner: demoBuilders[3],
    isLive: true,
    viewCount: 588,
    heartCount: 24,
  },
  {
    id: "demo-project-14",
    slug: "marketmap",
    status: "approved",
    hasPendingRevision: false,
    name: "MarketMap",
    tagline: "Compare competitor pages and spot positioning gaps.",
    description:
      "MarketMap captures market pages, clusters claims, and helps founders choose sharper positioning before launch.",
    projectUrl: "https://example.com/marketmap",
    category: categories[3],
    techStack: ["Next.js", "Playwright", "OpenAI"],
    projectTags: ["Marketing", "SaaS", "Workflow"],
    helpTags: ["Growth", "Product Feedback"],
    thumbnailUrl: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&w=1200&q=80",
    screenshotUrls: ["https://images.unsplash.com/photo-1504384308090-c894fdcc538d?auto=format&fit=crop&w=1200&q=80"],
    rejectionReason: null,
    reviewNotes: null,
    createdAt: "2026-03-30T12:00:00.000Z",
    updatedAt: "2026-04-07T12:00:00.000Z",
    submittedAt: "2026-03-30T12:00:00.000Z",
    revisionNumber: 1,
    owner: demoBuilders[0],
    isLive: true,
    viewCount: 721,
    heartCount: 33,
  },
  {
    id: "demo-project-15",
    slug: "mentorgrid",
    status: "approved",
    hasPendingRevision: false,
    name: "MentorGrid",
    tagline: "Match builders with the right reviewer for the next milestone.",
    description:
      "MentorGrid helps small communities route project feedback requests to members with relevant skills and availability.",
    projectUrl: "https://example.com/mentorgrid",
    category: categories[7],
    techStack: ["Laravel", "MySQL", "OpenAI"],
    projectTags: ["Community", "Marketplace", "Social"],
    helpTags: ["Collab", "Growth"],
    thumbnailUrl: "https://images.unsplash.com/photo-1521737604893-d14cc237f11d?auto=format&fit=crop&w=1200&q=80",
    screenshotUrls: ["https://images.unsplash.com/photo-1519389950473-47ba0277781c?auto=format&fit=crop&w=1200&q=80"],
    rejectionReason: null,
    reviewNotes: null,
    createdAt: "2026-03-29T12:00:00.000Z",
    updatedAt: "2026-04-06T12:00:00.000Z",
    submittedAt: "2026-03-29T12:00:00.000Z",
    revisionNumber: 2,
    owner: demoBuilders[1],
    isLive: true,
    viewCount: 514,
    heartCount: 21,
  },
  {
    id: "demo-project-16",
    slug: "inboxpilot",
    status: "approved",
    hasPendingRevision: false,
    name: "InboxPilot",
    tagline: "Draft follow-ups and task lists from high-noise inboxes.",
    description:
      "InboxPilot scans flagged threads, drafts replies, and turns unresolved asks into a prioritized work queue.",
    projectUrl: "https://example.com/inboxpilot",
    category: categories[4],
    techStack: ["Next.js", "Gmail API", "OpenAI"],
    projectTags: ["AI Agent", "Productivity", "Workflow"],
    helpTags: ["Security", "Performance"],
    thumbnailUrl: "https://images.unsplash.com/photo-1520607162513-77705c0f0d4a?auto=format&fit=crop&w=1200&q=80",
    screenshotUrls: ["https://images.unsplash.com/photo-1483058712412-4245e9b90334?auto=format&fit=crop&w=1200&q=80"],
    rejectionReason: null,
    reviewNotes: null,
    createdAt: "2026-03-28T12:00:00.000Z",
    updatedAt: "2026-04-05T12:00:00.000Z",
    submittedAt: "2026-03-28T12:00:00.000Z",
    revisionNumber: 1,
    owner: demoBuilders[5],
    isLive: true,
    viewCount: 866,
    heartCount: 39,
  },
]

export const demoComments: ProjectComment[] = [
  {
    id: "comment-1",
    projectId: "demo-project-1",
    userId: "demo-builder-2",
    user: demoBuilders[1],
    parentId: null,
    content: "This looks like exactly what I need for my team. Does it support nested prompt categories?",
    isHidden: false,
    createdAt: "2026-04-20T14:30:00.000Z",
    likeCount: 4,
    replies: [],
  },
  {
    id: "comment-2",
    projectId: "demo-project-1",
    userId: "demo-builder-1",
    user: demoBuilders[0],
    parentId: "comment-1",
    content: "Hey Noah! Yes, it does. You can organize them by team, product, or specific workflow tag.",
    isHidden: false,
    createdAt: "2026-04-20T15:45:00.000Z",
    likeCount: 2,
    replies: [],
  },
  {
    id: "comment-3",
    projectId: "demo-project-2",
    userId: "demo-builder-1",
    user: demoBuilders[0],
    parentId: null,
    content: "The design on this is super clean. Love the focus on classroom use cases.",
    isHidden: false,
    createdAt: "2026-04-22T09:15:00.000Z",
    likeCount: 5,
    replies: [],
  },
]
