import { categories } from "@/lib/constants"
import type { BuilderProfile, ProjectRecord, ProjectComment } from "@/lib/types"

export const demoBuilders: BuilderProfile[] = [
  {
    id: "demo-builder-1",
    email: "ava@example.com",
    fullName: "Ava Moreno",
    username: "avamoreno",
    avatarUrl: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=240&q=80",
    bio: "Shipping small AI tools and internal workflows for product teams.",
    isAdmin: true,
    twitterUrl: "https://twitter.com/avamoreno",
    githubUrl: "https://github.com/avamoreno",
    followerCount: 428,
    projectCount: 12,
  },
  {
    id: "demo-builder-2",
    email: "noah@example.com",
    fullName: "Noah Walker",
    username: "noahbuilds",
    avatarUrl: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=240&q=80",
    bio: "Focused on AI-native products for research, education, and support.",
    twitterUrl: "https://twitter.com/noahbuilds",
    followerCount: 156,
    projectCount: 5,
  },
]

export const demoProjects: ProjectRecord[] = [
  {
    id: "demo-project-1",
    slug: "promptlane",
    status: "approved",
    hasPendingRevision: false,
    name: "Promptlane",
    tagline: "Turn repeat prompts into reusable product playbooks.",
    description:
      "Promptlane helps teams capture the prompts, datasets, and notes behind recurring AI tasks so anyone on the team can reuse what works.",
    projectUrl: "https://example.com/promptlane",
    category: categories[0],
    techStack: ["Next.js", "Supabase", "OpenAI"],
    projectTags: ["SaaS", "Developer Tool", "Workflow"],
    helpTags: ["Security", "Design"],
    thumbnailUrl: "https://images.unsplash.com/photo-1558655146-d09347e92766?auto=format&fit=crop&w=1200&q=80",
    screenshotUrls: [
      "https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&w=1200&q=80",
    ],
    rejectionReason: null,
    reviewNotes: null,
    createdAt: "2026-04-15T12:00:00.000Z",
    updatedAt: "2026-04-17T12:00:00.000Z",
    submittedAt: "2026-04-15T12:00:00.000Z",
    revisionNumber: 1,
    owner: demoBuilders[0],
    isLive: true,
    viewCount: 1240,
    heartCount: 42,
  },
  {
    id: "demo-project-2",
    slug: "classnote-ai",
    status: "approved",
    hasPendingRevision: false,
    name: "Classnote AI",
    tagline: "A lesson recap companion for teachers and students.",
    description:
      "Teachers upload notes and generate clean summaries, quizzes, and study cards from a single workspace built for classroom use.",
    projectUrl: "https://example.com/classnote",
    category: categories[6],
    techStack: ["Next.js", "TypeScript", "Supabase"],
    projectTags: ["Education", "Productivity"],
    helpTags: ["Collab", "Product Feedback"],
    thumbnailUrl: "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=1200&q=80",
    screenshotUrls: [
      "https://images.unsplash.com/photo-1516321497487-e288fb19713f?auto=format&fit=crop&w=1200&q=80",
    ],
    rejectionReason: null,
    reviewNotes: null,
    createdAt: "2026-04-10T12:00:00.000Z",
    updatedAt: "2026-04-18T12:00:00.000Z",
    submittedAt: "2026-04-10T12:00:00.000Z",
    revisionNumber: 2,
    owner: demoBuilders[1],
    isLive: true,
    viewCount: 890,
    heartCount: 28,
  },
]

export const demoComments: ProjectComment[] = [
  {
    id: "comment-1",
    projectId: "demo-project-1",
    userId: "demo-builder-2",
    user: demoBuilders[1],
    content: "This looks like exactly what I need for my team. Does it support nested prompt categories?",
    createdAt: "2026-04-20T14:30:00.000Z",
    likeCount: 4,
  },
  {
    id: "comment-2",
    projectId: "demo-project-1",
    userId: "demo-builder-1",
    user: demoBuilders[0],
    content: "Hey Noah! Yes, it does. You can organize them by team, product, or specific workflow tag.",
    createdAt: "2026-04-20T15:45:00.000Z",
    likeCount: 2,
  },
  {
    id: "comment-3",
    projectId: "demo-project-2",
    userId: "demo-builder-1",
    user: demoBuilders[0],
    content: "The design on this is super clean. Love the focus on classroom use cases.",
    createdAt: "2026-04-22T09:15:00.000Z",
    likeCount: 5,
  },
]
